const database = {
  restaurant1: {
    customerId: "restaurant1",
    name: "Pour Wine Haus",
    address: "1820 Industrial St Los Angeles, CA 90021",
    phone: "(213) 327-0304",
    website: "http://pourhauswinebar.com/",
    logo: "https://res.cloudinary.com/db7ss52zt/image/upload/v1639668058/Menu%20Creator/Logo/Pour_Haus_Wine_Bar_Logo_uhxovp.jpg",
    menus: [
      {
        menuId: "foodId1",
        category: "snacks n stuff",
        name: "Chupacabra",
        rate: "none",
        price: 10,
        desc: "Baked goat cheese with house made marinara served with sliced garlic baguette",
        img: "",
      },
      {
        menuId: "foodId2",
        category: "snacks n stuff",
        name: "Bruschetta",
        rate: "none",
        price: 9,
        desc: "Traditional chopped roma tomato, basil, garlic & shaved parmesan on top of toasted baguette (we aren't shy with the garlic).",
        img: "https://res.cloudinary.com/db7ss52zt/image/upload/v1639674979/Menu%20Creator/Menu%20Pictures/Bruschetta_lnh2rf.png",
      },
      {
        menuId: "foodId3",
        category: "snacks n stuff",
        name: "Flatbread Pizza",
        rate: "none",
        price: 9,
        desc: "Mozzarella, artichoke heart, roasted onion, brushed w/ garlic oil",
        img: "https://res.cloudinary.com/db7ss52zt/image/upload/v1639681620/Menu%20Creator/Menu%20Pictures/Flatbread_Pizza_xyct0m.png",
      },
      {
        menuId: "foodId4",
        category: "snacks n stuff",
        name: "Mix N Match 4",
        rate: "none",
        price: 15,
        desc: "Cheese &/or charcuterie served w/ crackers, olives, nuts, tiny tart pickles, fig jam, truffle honey, quince & guava, and baguette & crackers. Your choice of 4 to 9 selections",
        img: "",
      },
      {
        menuId: "foodId5",
        category: "snacks n stuff",
        name: "Simple Salad",
        rate: "none",
        price: 9.5,
        desc: "Feta cheese, heirloom tomato, cucumber, basil, avocado & roasted corn splashed w/ olive oil and balsamic.",
        img: "",
      },
      {
        menuId: "foodId6",
        category: "snacks n stuff",
        name: "Papitas Bravas",
        rate: "none",
        price: 8,
        desc: "House-made turkey sloppy joe's on Hawaiian breadettes topped w/ our mayo-free cilantro scallion slaw",
        img: "https://res.cloudinary.com/db7ss52zt/image/upload/v1639681668/Menu%20Creator/Menu%20Pictures/Papitas_Bravas_csh1cl.png",
      },
      {
        menuId: "sandwichId1",
        category: "lord sandwich",
        name: "Croque Monsieur",
        rate: "none",
        price: 9,
        desc: "Pressed gruyere & black forest ham baked w/ bechamel sauce. Madame the Croque (add 2 baked eggs) $9.00 - $11.50",
        img: "",
      },
      {
        menuId: "sandwichId2",
        category: "lord sandwich",
        name: "Sloppy Sliders",
        rate: "none",
        price: 10,
        desc: "House-made turkey sloppy joe's on Hawaiian breadettes topped w/ our mayo-free cilantro scallion slaw",
        img: "",
      },
      {
        menuId: "sandwichId3",
        category: "lord sandwich",
        name: "Viet Nom Nom",
        rate: "none",
        price: 11,
        desc: "Grilled chicken, basil, cilantro, cabbage, jalapeño & pepper-jack cheese w/ a chicken lime au jus dip.",
        img: "https://res.cloudinary.com/db7ss52zt/image/upload/v1639681669/Menu%20Creator/Menu%20Pictures/Viet_Nom_Nom_up9vot.png",
      },
      {
        menuId: "sandwichId4",
        category: "lord sandwich",
        name: "Grilled Cheese",
        rate: "none",
        price: 9,
        desc: "Cheddar, pear, & honey",
        img: "",
      },
      {
        menuId: "sandwichId5",
        category: "lord sandwich",
        name: "Americano",
        rate: "none",
        price: 10,
        desc: "Slowly braised short rib, garlic butter, horseradish cream sauce grilled in ciabatta rolls.",
        img: "",
      },
      {
        menuId: "substantialId1",
        category: "substantial",
        name: "Sunday Pot Roast",
        rate: "none",
        price: 11,
        desc: "Served everyday w/ potato, carrot, celery & horseradish sauce",
        img: "",
      },
      {
        menuId: "substantialId1",
        category: "substantial",
        name: "Mac n Cheese",
        rate: "none",
        price: 10,
        desc: "arfalle pasta with a blend of four cheeses served with a side of siracha",
        img: "",
      },
      {
        menuId: "substantialId1",
        category: "substantial",
        name: "Bird Haus",
        rate: "none",
        price: 10,
        desc: "Dark meat chicken, cooked slowly & deliberately in sweet/spicy adobo",
        img: "https://res.cloudinary.com/db7ss52zt/image/upload/v1639681850/Menu%20Creator/Menu%20Pictures/Bird_Haus_soukge.png",
      },
    ],
  },
};

export default database;
